### ISSUE TITLE
fastcraft-v17 error with spigot 1.8.7

### ISSUE THREAD

**Issue by xhouserx** [xhouserx/fastcraft-v17#1]
[20:43:04] [Server thread/ERROR]: Could not pass event InventoryOpenEvent to FastCraft v17
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-6d16e64-b105298]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-6d16e64-b105298]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:728) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:714) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
    at net.minecraft.server.v1_8_R3.EntityPlayer.openTileEntity(EntityPlayer.java:636) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
    at net.minecraft.server.v1_8_R3.BlockWorkbench.interact(SourceFile:29) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
    at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:496) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:736) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_71]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_71]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.NoSuchMethodError: java.util.HashMap.getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    at co.kepler.fastcraft.InventoryManager.checkIfTempDisabled(InventoryManager.java:108) ~[?:?]
    at co.kepler.fastcraft.InventoryManager.onInventoryOpen(InventoryManager.java:79) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor306.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-6d16e64-b105298]
    ... 20 more

**Comment by RoboMWM** [comment]
Running Java 8 update 45, some fairly-recent build of PaperSpigot: http://www.hastebin.com/ebosesazox.avrasm
